# Generated by Django 2.0 on 2018-01-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0002_t_common_qu_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='t_common_qu_info',
            new_name='t_common_qu',
        ),
    ]
